### ISSUE TITLE
problem about torch

### ISSUE THREAD

**Issue by LiyuanLucasLiu** [yoonkim/word-char-rnn#16]
Hi, Great work! But I met some problems while trying to run the code myself.
I installed Lua following [http://torch.ch/docs/getting-started.html#_ ]  , and installed all required packages, but the Lua crashed when I tried to train the model.

the error message is:

```
/home/s2free/torch/install/bin/luajit: /home/s2free/torch/install/share/lua/5.1/
trepl/init.lua:384: /home/s2free/torch/install/share/lua/5.1/torch/init.lua:102:
 class nn.Squeeze has been already assigned a parent class

stack traceback:
    [C]: in function 'error'
    /home/s2free/torch/install/share/lua/5.1/trepl/init.lua:384: in function
 'require'
    main.lua:14: in main chunk
    [C]: in function 'dofile'
    ...free/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main
 chunk
    [C]: at 0x00406240
```

And I found that if I comment the 384 line of /home/s2free/torch/install/share/lua/5.1/trepl/init.lua, the code won't break.

As I'm a rookie on Torch, I'm really curious about why this would happen.

Thanks a lot!

**Comment by aigujin** [comment]
I got exactly the same error. I hope the developer would react on this issue.

**Comment by yoonkim** [comment]
hi, this seems to due to the most recent version of Torch having implemented a module with the same name (nn.Squeeze). It should work now--would you guys mind giving it a try? Thanks!

**Comment by aigujin** [comment]
Yes, it's working now! Thanks

**Comment by LiyuanLucasLiu** [comment]
Yes, Thanks!
