### ISSUE TITLE
How is the matrix C-k padded with zeros?

### ISSUE THREAD

**Issue by felicialiu** [yoonkim/word-char-rnn#21]
One of the footnotes of the paper states that the character-level representation matrix C-k is zero-padded so that the input to TDNN all have fixed size like batch_size x max_word_l x char_vec_size. Is the original character-level representation padded with zeros at the top, botton, or is it centered? I can't seem to find in the code where this is done.

So for example if you have:
`0.5030  0.4816  0.9014  0.1423  1.2905`
 `-0.6805 -1.1351 -2.2197 -0.1245 -1.7221`
`-0.6821  1.3445 -1.3602  1.6282  1.3519`

What does the padded result look like?

`0.0000  0.0000  0.0000  0.0000 0.0000`
`0.0000  0.0000  0.0000  0.0000 0.0000`
`0.5030  0.4816  0.9014  0.1423  1.2905`
`-0.6805 -1.1351 -2.2197 -0.1245 -1.7221`
`-0.6821  1.3445 -1.3602  1.6282  1.3519`

`0.0000  0.0000  0.0000  0.0000 0.0000`
`0.5030  0.4816  0.9014  0.1423  1.2905`
 `-0.6805 -1.1351 -2.2197 -0.1245 -1.7221`
`-0.6821  1.3445 -1.3602  1.6282  1.3519`
`0.0000  0.0000  0.0000  0.0000 0.0000`

`0.5030  0.4816  0.9014  0.1423  1.2905`
 `-0.6805 -1.1351 -2.2197 -0.1245 -1.7221`
`-0.6821  1.3445 -1.3602  1.6282  1.3519`
`0.0000  0.0000  0.0000  0.0000 0.0000`
`0.0000  0.0000  0.0000  0.0000 0.0000`

**Comment by yoonkim** [comment]
It is padded at bottom.
